@startuml
actor user
participant client
collections protocol

client-[#green]>user: ask_input()
note over user #tomato: verify
user-[#tomato]>client : input

client -> protocol : protocol_client_send()
note right #tomato: V
client <[#palegreen]- protocol : protocol_client_receive()
note right #palegreen: 3OK
note left #palegreen: OK
user <[#palegreen]- client : print()

@enduml

