@startuml
participant server
collections protocol
boundary sudoku_dispatcher
entity sudoku

note over protocol #tomato: V
server <[#tomato]-protocol: protocol_server_receive()
server-[#tomato]>sudoku_dispatcher : dispatch(command)
sudoku_dispatcher-[#green]>o sudoku : sudoku_verify()

note right sudoku #palegreen: true
sudoku_dispatcher <[#palegreen]- sudoku

note left sudoku_dispatcher #palegreen: 3OK
sudoku_dispatcher-[#palegreen]>server

server -[#palegreen]>protocol: protocol_server_send()
note over protocol #palegreen: OK
note over protocol #yellow: responds \nto client

@enduml

